therapy_words = ['sars', 'cov', 'disease', 'respiratory', 'infection', 'clinical', 'severe', 'acute', 'results',
                 'cases', 'treatment', 'studies', 'syndrome', 'may', 'symptoms', 'health', 'methods', 'risk', 'data',
                 'associated', 'viral', 'review', 'virus', 'patient', 'case', 'children', 'years', 'pcr', 'care',
                 'positive', 'hospital', 'diagnosis', 'pneumonia', 'infections', 'lung', 'reported', 'days',
                 'mortality', 'related', 'used', 'also', 'two', 'evidence', 'age', 'time', 'research', 'common', 'high',
                 'one', 'use', 'including', 'among', 'higher', 'pandemic', 'analysis', 'included', 'findings', 'cells',
                 'based', 'outcomes', 'background', 'conclusions', 'novel', 'showed', 'transmission', 'diseases',
                 'confirmed', 'however', 'laboratory', 'increased', 'first', 'group', 'early', 'compared', 'well',
                 'non', 'identified', 'significantly', 'pulmonary', 'human', 'blood', 'cell', 'total', 'asymptomatic',
                 'conclusion', 'tests', 'levels', 'lower', 'samples', 'therapy', 'control', 'infected', 'caused',
                 'chest', 'inflammatory', 'fever', 'admission', 'test', 'severity', 'report']
diagnosis_words = ['results', 'used', 'methods', 'time', 'group', 'data', 'risk', 'clinical', 'use', 'patient', 'two',
                   'treatment', 'compared', 'based', 'performed', 'care', 'surgery', 'mean', 'model', 'may', 'one',
                   'background', 'control', 'conclusions', 'disease', 'significant', 'laparoscopic', 'days', 'pandemic',
                   'infection', 'analysis', 'cases', 'influenza', 'high', 'associated', 'approach', 'rate',
                   'significantly', 'age', 'complications', 'total', 'outcomes', 'groups', 'surgical', 'medical',
                   'different', 'less', 'postoperative', 'management', 'system', 'however', 'health', 'respiratory',
                   'well', 'conclusion', 'hospital', 'higher', 'period', 'related', 'pressure', 'single', 'also',
                   'years', 'first', 'respectively', 'case', 'method', 'increased', 'included', 'including', 'positive',
                   'factors', 'three', 'number', 'min', 'blood', 'objective', 'underwent', 'showed', 'technique',
                   'studies', 'review', 'among', 'models', 'lower', 'present', 'range', 'virus', 'quality',
                   'information', 'procedures', 'effective', 'year', 'months', 'observed', 'acute', 'non', 'research',
                   'without', 'mortality']
prognosis_words = ['virus', 'cells', 'protein', 'infection', 'viral', 'sars', 'cov', 'cell', 'human', 'results', 'rna',
                   'also', 'respiratory', 'high', 'expression', 'disease', 'may', 'proteins', 'analysis', 'immune',
                   'associated', 'activity', 'infected', 'two', 'gene', 'specific', 'host', 'based', 'replication',
                   'data', 'vaccine', 'potential', 'mice', 'type', 'however', 'different', 'new', 'response',
                   'clinical', 'ace', 'binding', 'antibodies', 'treatment', 'development', 'influenza', 'found',
                   'infections', 'one', 'including', 'identified', 'studies', 'showed', 'used', 'antibody', 'sequence',
                   'important', 'risk', 'novel', 'antiviral', 'methods', 'genome', 'system', 'severe', 'role', 'could',
                   'anti', 'induced', 'well', 'strains', 'acute', 'genes', 'vaccines', 'observed', 'cellular', 'ifn',
                   'infectious', 'receptor', 'compared', 'first', 'non', 'group', 'acid', 'three', 'time', 'responses',
                   'strain', 'dna', 'present', 'molecular', 'related', 'increased', 'significant', 'diseases', 'like',
                   'positive', 'detected', 'vitro', 'levels', 'target']
etiology_words = ['health', 'disease', 'pandemic', 'cases', 'care', 'public', 'virus', 'risk', 'results', 'infection',
                  'new', 'data', 'clinical', 'countries', 'measures', 'epidemic', 'number', 'high', 'may', 'also',
                  'social', 'treatment', 'based', 'outbreak', 'human', 'infectious', 'viruses', 'control', 'time',
                  'methods', 'use', 'spread', 'among', 'many', 'healthcare', 'associated', 'population', 'china',
                  'global', 'world', 'diseases', 'model', 'one', 'impact', 'system', 'infections', 'analysis',
                  'respiratory', 'different', 'first', 'cancer', 'people', 'rate', 'response', 'reported', 'hospital',
                  'group', 'potential', 'however', 'significant', 'studies', 'including', 'influenza', 'current',
                  'surgery', 'provide', 'medical', 'transmission', 'research', 'important', 'review', 'well', 'case',
                  'viral', 'early', 'management', 'strategies', 'mortality', 'systems', 'information', 'need', 'used',
                  'related', 'days', 'patient', 'level', 'novel', 'due', 'non', 'major', 'factors', 'national',
                  'states', 'compared', 'development', 'sars', 'within', 'deaths', 'community', 'could']
meaning_words = ['virus', 'protein', 'cells', 'data', 'viruses', 'analysis', 'two', 'viral', 'also', 'human',
                 'infection', 'health', 'disease', 'high', 'infected', 'new', 'model', 'strains', 'different', 'cell',
                 'results', 'based', 'pandemic', 'used', 'specific', 'novel', 'species', 'may', 'gene', 'vaccine',
                 'sequence', 'related', 'activity', 'genome', 'antibodies', 'found', 'one', 'first', 'infectious',
                 'including', 'showed', 'acid', 'binding', 'strain', 'world', 'countries', 'three', 'system', 'number',
                 'important', 'proteins', 'replication', 'could', 'spread', 'ibv', 'research', 'antiviral', 'present',
                 'well', 'antibody', 'time', 'provide', 'china', 'available', 'sequences', 'amino', 'mice', 'diseases',
                 'however', 'treatment', 'public', 'development', 'sars', 'dna', 'response', 'cases', 'control',
                 'transmission', 'host', 'many', 'assay', 'information', 'structural', 'identified', 'cov', 'genes',
                 'structure', 'potential', 'detection', 'rna', 'major', 'type', 'effective', 'level', 'effect',
                 'methods', 'influenza', 'developed', 'region']
prevention_words = ['infection', 'disease', 'results', 'clinical', 'risk', 'virus', 'children', 'age', 'associated',
                    'influenza', 'group', 'cases', 'infections', 'severe', 'years', 'positive', 'methods', 'data',
                    'viruses', 'mortality', 'days', 'viral', 'samples', 'compared', 'among', 'pcr', 'one', 'may',
                    'analysis', 'high', 'two', 'hospital', 'treatment', 'care', 'time', 'significantly', 'acute',
                    'higher', 'studies', 'detected', 'pneumonia', 'rate', 'background', 'based', 'factors', 'increased',
                    'human', 'conclusions', 'sars', 'used', 'common', 'outcomes', 'cov', 'control', 'test', 'detection',
                    'included', 'non', 'groups', 'pandemic', 'blood', 'lower', 'total', 'identified', 'patient',
                    'symptoms', 'incidence', 'also', 'first', 'showed', 'confirmed', 'found', 'respectively', 'levels',
                    'day', 'number', 'health', 'conclusion', 'collected', 'significant', 'three', 'laboratory', 'case',
                    'mean', 'population', 'reported', 'tests', 'pathogens', 'severity', 'performed', 'however', 'rsv',
                    'including', 'model', 'year', 'tested', 'use', 'type', 'period']